services:
  kali:
    build:
      context: kali/
    image: kali:${KALI_VERSION}
    hostname: kali

  snort:
    build:
      context: snort/
      dockerfile: Dockerfile
    image: snort:${SNORT_VERSION}
    hostname: snort

  tomcat:
    build:
      context: tomcat/
      dockerfile: Dockerfile
    image: tomcat:${TOMCAT_VERSION}

  caldera:
    build:
      context: ../deps/caldera/
      dockerfile: ../../Dockerfiles/caldera/Dockerfile
    image: caldera:${CALDERA_VERSION}

  vuln_apache:
    build:
      context: vuln_apache/
    image: vuln_apache:${VULN_APACHE_VERSION}

  monkey_island:
    build:
      context: monkey_island/
      dockerfile: Dockerfile
    image: monkey_island:${MONKEY_ISLAND_VERSION}
